-- Date: 2024-10-16 Alex Day
-- This SQL script combines the data from three different tables into one table
CREATE TABLE "combinedtables"."combined_order" AS --rename the table to your own DB and whatever table name you want
SELECT 
    'tablename' AS source, --this creates a column for the source of the data
    order_id, --all of these columns are from the ota_order table. Change them to fit your own table's columns
    order_code,
    customer_id,
    ext_id,
    parent_id,
    salesman_account,
    order_name,
    order_comp_name,
    order_comp_depa,
    order_tel,
    order_mobile_phone,
    order_email,
    order_stage,
    total_price,
    payment_date,
    tax,
    tax_rate,
    tax_settings,
    qualified_invoice,
    cod_cost,
    order_zip,
    order_pref,
    order_address01,
    order_address02,
    order_address03,
    payment,
    payment_option,
    shipping_cost,
    final_price,
    use_point,
    get_point,
    text,
    info,
    order_memo,
    order_time,
    api_status,
    payment_fin,
    status,
    af_id,
    enquete1,
    enquete2,
    enquete3,
    enquete4,
    enquete5,
    relation_id,
    customer_custom1,
    customer_custom2,
    customer_custom3,
    partition_0
FROM 
    "auroratos3exporttest"."tablename.order" --insert your own DB and table name here

UNION ALL --this is the SQL command to combine the data from the other tables

SELECT 
    'tablename' AS source,
    order_id,
    order_code,
    customer_id,
    ext_id,
    parent_id,
    salesman_account,
    order_name,
    order_comp_name,
    order_comp_depa,
    order_tel,
    order_mobile_phone,
    order_email,
    order_stage,
    total_price,
    payment_date,
    tax,
    tax_rate,
    tax_settings,
    qualified_invoice,
    cod_cost,
    order_zip,
    order_pref,
    order_address01,
    order_address02,
    order_address03,
    payment,
    payment_option,
    shipping_cost,
    final_price,
    use_point,
    get_point,
    text,
    info,
    order_memo,
    order_time,
    api_status,
    payment_fin,
    status,
    af_id,
    enquete1,
    enquete2,
    enquete3,
    enquete4,
    enquete5,
    relation_id,
    customer_custom1,
    customer_custom2,
    customer_custom3,
    partition_0
FROM 
    "auroratos3exporttest"."tablename_order" --insert your own DB and table name here

UNION ALL

SELECT 
    'tablename' AS source,
    order_id,
    order_code,
    customer_id,
    ext_id,
    parent_id,
    salesman_account,
    order_name,
    order_comp_name,
    order_comp_depa,
    order_tel,
    order_mobile_phone,
    order_email,
    order_stage,
    total_price,
    payment_date,
    tax,
    tax_rate,
    tax_settings,
    qualified_invoice,
    cod_cost,
    order_zip,
    order_pref,
    order_address01,
    order_address02,
    order_address03,
    payment,
    payment_option,
    shipping_cost,
    final_price,
    use_point,
    get_point,
    text,
    info,
    order_memo,
    order_time,
    api_status,
    payment_fin,
    status,
    af_id,
    enquete1,
    enquete2,
    enquete3,
    enquete4,
    enquete5,
    relation_id,
    customer_custom1,
    customer_custom2,
    customer_custom3,
    partition_0
FROM 
    "auroratos3exporttest"."tablename_order"; --insert your own DB and table name here